---

# critical for the postgresql_user and postgresql_db plugins to work as expected
# also required for plugins running as {{ netbox.user.name }}
# my common role already installs it, added here to make this role more self-contained
- name: "Make sure access control list (ACL) utilities are installed"
  ansible.builtin.apt:
    name: acl
    state: present

- name: "Create pgsql database user {{ netbox.config.database.user }}"
  community.postgresql.postgresql_user:
    name: "{{ netbox.config.database.user }}"
    password: "{{ netbox.config.database.pass }}"
    # https://dba.stackexchange.com/a/263911
    role_attr_flags: CREATEDB,CREATEROLE,INHERIT,NOSUPERUSER,LOGIN
    encrypted: yes
    state: present
    expires: infinity
    port: "{{ netbox.config.database.port }}"
  become: true
  become_user: "{{ netbox.config.database.admin_username }}"

# check what pgsql databases exist
# https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_info_module.html
- name: Collect info on all existing pgsql databases
  community.postgresql.postgresql_info:
    filter:
      - "databases"
  become: true
  become_user: "{{ netbox.config.database.admin_username }}"
  register: netbox_psql_info

- name: "Create empty database {{ netbox.config.database.name }} (if not already exist)"
  community.postgresql.postgresql_db:
    name: "{{ netbox.config.database.name }}"
    encoding: UTF-8
    state: present
    owner: "{{ netbox.config.database.user }}"
    port: "{{ netbox.config.database.port }}"
  become: true
  become_user: "{{ netbox.config.database.admin_username }}"
  when: "netbox.config.database.name not in netbox_psql_info.databases"

# Param 'priv' of module postgresql_user is deprecated.
- name: "Grant all privileges on {{ netbox.config.database.name }} to user {{ netbox.config.database.user }}"
  community.postgresql.postgresql_privs:
    database: "{{ netbox.config.database.name }}"
    type: database
    privs: ALL
    role: "{{ netbox.config.database.user }}"
    state: present
  become: true
  become_user: "{{ netbox.config.database.admin_username }}"
