---

- name: "Download Netbox tarball v{{ netbox_version }}"
  ansible.builtin.get_url:
    url: "https://github.com/netbox-community/netbox/archive/refs/tags/v{{ netbox_version }}.tar.gz"
    dest: "{{ netbox.path.downloads }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: u=rw,go=r
  register: netbox_installer

- name: "Ensure {{ netbox.path.base }} directory exists"
  ansible.builtin.file:
    path: "{{ netbox.path.base }}"
    state: directory
    owner: "{{ netbox.user.name }}"
    group: "{{ netbox.user.name }}"
  register: netbox_dir

- name: "Unpack Netbox tarball into {{ netbox.path.base }}"
  ansible.builtin.unarchive:
    src: "{{ netbox_installer.dest }}"
    dest: "{{ netbox.path.base }}"
    remote_src: yes
    owner: "{{ netbox.user.name }}"
    group: "{{ netbox.user.name }}"
    extra_opts: "--strip-components=1"
