---

- ansible.builtin.import_tasks: version-check.yml

- ansible.builtin.import_tasks: user.yml
- ansible.builtin.import_tasks: database.yml
- ansible.builtin.import_tasks: install.yml

# contains all tasks that write to the database
- ansible.builtin.import_tasks: configure.yml

- ansible.builtin.import_tasks: gunicorn.yml
