---

- name: Merge default variable
  ansible.builtin.import_tasks: merge-defaults.yml
  tags:
    - default
    - backups-only
    - config-only


- name: Setup NetBox
  when: not (host_restrictions | bool) or group_names is not search("workstation")
  block:

    - ansible.builtin.import_tasks: version-check.yml
      tags:
        - backups-only
        - config-only

    - ansible.builtin.import_tasks: user.yml
      tags: config-only

    - ansible.builtin.import_tasks: database.yml
      tags: config-only

    - ansible.builtin.import_tasks: dependencies.yml

    - ansible.builtin.import_tasks: restore.yml
      when: netbox_restore.overwrite | bool

    # not needed when restoring from backup
    - ansible.builtin.import_tasks: install.yml
      when: not (netbox_restore.overwrite | bool)

    # not needed when restoring from backup
    - ansible.builtin.import_tasks: config/main.yml
      when: not (netbox_restore.overwrite | bool)
      tags: config-only

    - ansible.builtin.import_tasks: config/systemd.yml
      tags: config-only

    - ansible.builtin.import_tasks: upgrade.yml
      when: >
        (netbox_restore.overwrite | bool) or
        netbox_installer.changed or
        netbox_dir.changed or
        netbox_iversion != netbox_version

    - ansible.builtin.import_tasks: gunicorn.yml

    - name: Backup database and working directory
      ansible.builtin.import_tasks: backup.yml
      # no need to backup if we just restored from backup
      when: not (netbox_restore.overwrite | bool)
      tags: backups-only
  # END OF BLOCK


- ansible.builtin.import_tasks: desktop-entry.yml
  when: not (host_restrictions | bool) or group_names is search("workstation")
  tags: desktop-entry

- ansible.builtin.import_tasks: log-git-state.yml
  tags:
    - log-git-state
    - backups-only
    - config-only
