---

# the upgrade script keeps running without regard to our venv
# even when setting PYTHON={{ netbox.base_path }}/venv/bin/python3.7
# like the docs suggested
# I see no other recourse than to edit the upgrade.sh script in-place
# before running it
- name: Make sure upgrade script uses venv
  ansible.builtin.lineinfile:
    path: "{{ netbox.base_path }}/upgrade.sh"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: "^PYTHON=", line: "PYTHON={{ netbox.base_path }}/venv/bin/python{{ ppa_deadsnakes.version }}" }
    - { regexp: "^PIP=", line: "PIP={{ netbox.base_path }}/venv/bin/pip{{ ppa_deadsnakes.version }}" }

# with config in place, it's now time to run the upgrade.sh script
# this script must be run whether the installation is new or upgraded in place
# among other things, it runs database schema migrations
# https://stackoverflow.com/questions/48174599/is-there-a-single-line-way-to-run-a-command-in-a-python-venv
# https://unix.stackexchange.com/questions/409609/how-to-run-a-command-inside-a-virtualenv-using-systemd
- name: Run Netbox upgrade.sh script
  ansible.builtin.command: ./upgrade.sh
  args:
    chdir: "{{ netbox.base_path }}"
  become: true
  become_user: "{{ wallatinyarchive.user.netbox.name }}"
