---

# https://netbox.readthedocs.io/en/stable/installation/3-netbox/#create-the-netbox-system-user
# Create a system user account named netbox.

# I don't expect netbox media to take much space, so see no need to put it on BAY.
# Simply including media in the backup job should be enough.

- name: Create Netbox user and group
  ansible.builtin.user:
    name: "{{ netbox.user.name }}"
    shell: "{{ netbox.user.shell }}"
    home: "{{ netbox.path.base }}"
    create_home: no
    comment: "NetBox user"
    system: yes

# Add the netbox user to the redis group
- name: Allow the netbox user to connect to the redis socket
  ansible.builtin.command: usermod -a -G redis {{ netbox.user.name }}
  when: netbox.config.redis.socket | bool
