---

- name: "Set fact netbox_version"
  ansible.builtin.set_fact:
    netbox_version: "{{ netbox.version }}"


- name: Find latest available Netbox version
  when: netbox_version == "latest"
  block:

    - name: Gather latest Netbox release information from github
      ansible.builtin.uri:
        method: GET
        status_code: 200
        url: https://api.github.com/repos/netbox-community/netbox/releases/latest
      run_once: true
      delegate_to: localhost
      register: netbox_uri

    # # [1:] strips the first character ("v" in this case) from the version string
    - name: Latest Netbox version
      ansible.builtin.set_fact:
        netbox_version: "{{ netbox_uri.json.tag_name[1:] }}" # 3.1.8
  # END OF BLOCK


- name: "Check for existing install at {{ netbox.path.base }}"
  ansible.builtin.stat:
    path: "{{ netbox.path.base }}/netbox/netbox/settings.py"
  changed_when: false
  register: netbox_canary

# /opt/netbox/netbox/netbox/settings.py
# VERSION = '3.2.7'
- name: Find installed version of NetBox
  when: netbox_canary.stat.exists | bool
  ansible.builtin.shell: >
    awk '/^VERSION/{print $3}'
    {{ netbox.path.base }}/netbox/netbox/settings.py |
    sed "s/'//g"
  register: netbox_installedv_cmd

- ansible.builtin.set_fact:
    netbox_iversion: "{{ netbox_installedv_cmd.stdout }}"
