---

# let's implement the housekeeping cronjob as a systemd timer
- name: Create systemd timer for Netbox housekeeping
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: u=rw,go=r
  loop:
    - netbox-housekeeping.service
    - netbox-housekeeping.timer

- name: Enable and start the Netbox housekeeping timer
  ansible.builtin.systemd:
    name: netbox-housekeeping.timer
    enabled: yes
    state: started
    scope: system
    daemon_reload: yes
