---

- name: restart netbox services
  listen: restart netbox services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - netbox.service
    - netbox-rq.service

- name: run housekeeping
  listen: restart netbox services
  ansible.builtin.command: >
    venv/bin/python{{ python_major_version}} netbox/manage.py housekeeping
  args:
    chdir: "{{ netbox.path.base }}"
  become: true
  become_user: "{{ netbox.user.name }}"

- name: Update desktop entry database
  ansible.builtin.command: >
    /usr/bin/update-desktop-database -v {{ xdg_desktop_entries }}
